
version: 0.2

phases:
  install:
    commands:
      - echo " Checking the date "
      - echo $date 

#      - "apt install unzip -y"
#      - "wget https://releases.hashicorp.com/terraform_1.3.5/terraform_1.3.5_linux_arm.zip"
#      - "unzip terraform_1.3.5_linux_arm.zip"
#      - "mv terraform /usr/local/bin/"
  
     - echo "Adding terraform repository"
     - apt-get update && sudo apt-get install -y gnupg software-properties-common
     - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
     - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
     - sudo apt update -y && sudo apt-get install terraform
#      - "apt install unzip -y"
#      - "wget https://releases.hashicorp.com/terraform/0.14.10/terraform_0.14.10_linux_amd64.zip"
#      - "unzip terraform_0.14.10_linux_amd64.zip"
#      - "mv terraform /usr/local/bin/"
  
  pre_build:
    commands:
      - pwd
      - ls -l
      - cd terraform/HelloTerraform/
      - ls -l
      - terraform init
  build:
    commands:
#       - terraform $TF_COMMAND -auto-approve
      - terraform apply --auto-approve 

  post_build:
    commands:
      - echo terraform $TF_COMMAND completed on '$date'



